# Generated by Django 5.2.1 on 2026-03-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallettransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("FUNDING", "Wallet Funding"),
                    ("ORDER_PAYMENT", "Order Payment"),
                    ("REFUND", "Refund"),
                    ("REVERSAL", "Reversal"),
                    ("ADMIN_ADJUSTMENT", "Admin Adjustment"),
                    ("TRANSFER", "Wallet Transfer"),
                ],
                max_length=50,
            ),
        ),
    ]
