# Generated by Django 5.2.1 on 2026-02-24 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("FLUTTERWAVE", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("WALLET_FUNDING", "Wallet Funding"),
                            ("ORDER_PAYMENT", "Order Payment"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("payment_url", models.URLField(blank=True, null=True)),
                (
                    "access_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("initialization_response", models.JSONField(blank=True, null=True)),
                ("verification_response", models.JSONField(blank=True, null=True)),
                ("webhook_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_received", models.BooleanField(default=False)),
                ("webhook_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("PAYSTACK", "Paystack"),
                            ("FLUTTERWAVE", "Flutterwave"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("headers", models.JSONField(default=dict)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_webhook_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="payment_tra_user_id_001d5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["reference"], name="payment_tra_referen_451c50_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["gateway_reference"], name="payment_tra_gateway_baea68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status"], name="payment_tra_status_137fde_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["-created_at"], name="payment_web_created_72f5d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentwebhooklog",
            index=models.Index(
                fields=["gateway", "event_type"], name="payment_web_gateway_6232a3_idx"
            ),
        ),
    ]
