# Generated by Django 5.2.1 on 2026-03-09 13:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                            ("VERVE", "Verve"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "card_category",
                    models.CharField(
                        choices=[("VIRTUAL", "Virtual"), ("PHYSICAL", "Physical")],
                        default="VIRTUAL",
                        max_length=20,
                    ),
                ),
                ("last_four", models.CharField(max_length=4)),
                ("holder_name", models.CharField(max_length=100)),
                ("expiry_month", models.PositiveSmallIntegerField()),
                ("expiry_year", models.PositiveSmallIntegerField()),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cashback_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "color_gradient",
                    models.CharField(
                        blank=True,
                        default="from-blue-600 to-blue-800",
                        help_text="Tailwind gradient classes e.g. 'from-blue-600 to-blue-800'",
                        max_length=120,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        default="#3b82f6",
                        help_text="Hex accent colour for the card e.g. '#3b82f6'",
                        max_length=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("FROZEN", "Frozen"),
                            ("BLOCKED", "Blocked"),
                            ("EXPIRED", "Expired"),
                            ("PENDING", "Pending"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "external_card_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Card ID returned by issuer API (Flutterwave, etc.)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CardTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SHOPPING", "Shopping"),
                            ("FOOD_DINING", "Food & Dining"),
                            ("ENTERTAINMENT", "Entertainment"),
                            ("UTILITIES", "Utilities"),
                            ("TRAVEL", "Travel"),
                            ("HEALTH", "Health"),
                            ("INCOME", "Income"),
                            ("TRANSFER", "Transfer"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "merchant_icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon identifier shown in the frontend",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="cards.card",
                    ),
                ),
                (
                    "payment_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="card_transaction",
                        to="payments.paymenttransaction",
                    ),
                ),
            ],
            options={
                "db_table": "card_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(
                fields=["user", "-created_at"], name="cards_user_id_96584f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["status"], name="cards_status_90adc2_idx"),
        ),
        migrations.AddIndex(
            model_name="cardtransaction",
            index=models.Index(
                fields=["card", "-created_at"], name="card_transa_card_id_7097c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cardtransaction",
            index=models.Index(fields=["status"], name="card_transa_status_fc1966_idx"),
        ),
        migrations.AddIndex(
            model_name="cardtransaction",
            index=models.Index(
                fields=["reference"], name="card_transa_referen_edec1d_idx"
            ),
        ),
    ]
